#
# TABLE STRUCTURE FOR: Categoria
#

USE comportamento_digital;

INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (1, 'Rogahn-Mertz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (2, 'Koss, Lockman and Corwin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (3, 'Murphy-Dickens');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (4, 'Hamill-Purdy');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (5, 'Bechtelar-Medhurst');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (6, 'Schmitt Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (7, 'Kuvalis-Stiedemann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (8, 'Moore, Ebert and Tromp');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (9, 'Franecki-Reynolds');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (10, 'Zemlak-Goldner');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (11, 'Mohr, Bergstrom and Bayer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (12, 'Aufderhar-Senger');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (13, 'Dibbert and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (14, 'Brakus-Thompson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (15, 'Hauck-Hessel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (16, 'Goyette, Grady and Macejkovic');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (17, 'Langworth-Carroll');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (18, 'Cassin, Cummerata and Bailey');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (19, 'Boyle, Breitenberg and Smitham');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (20, 'Hickle, Effertz and Dickens');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (21, 'Raynor, Kulas and Hessel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (22, 'Rosenbaum-Marvin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (23, 'Ebert PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (24, 'Denesik Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (25, 'Bashirian, Denesik and Thompson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (26, 'Sawayn-Ruecker');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (27, 'Casper, Becker and Kihn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (28, 'Schowalter, Feil and Hahn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (29, 'Quigley, Ryan and Collins');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (30, 'Hills-Lockman');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (31, 'Larson, Keebler and Stark');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (32, 'Kutch and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (33, 'Leffler-Pfeffer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (34, 'Ortiz PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (35, 'Roob, Zieme and Bernhard');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (36, 'Larkin-Kemmer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (37, 'Macejkovic, Spencer and Paucek');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (38, 'Lakin, Kshlerin and Casper');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (39, 'Kulas PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (40, 'Jacobson Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (41, 'Terry and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (42, 'Kozey Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (43, 'Kessler Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (44, 'Rau, Romaguera and Runte');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (45, 'Witting-O\'Conner');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (46, 'Reynolds-Connelly');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (47, 'Erdman, Lakin and Wiegand');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (48, 'Gutkowski-Murphy');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (49, 'Erdman PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (50, 'Kuhic, Auer and Konopelski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (51, 'Sipes LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (52, 'Jacobs-Mann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (53, 'Hermann LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (54, 'Schmitt-Padberg');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (55, 'Klein, Leannon and Zulauf');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (56, 'Grimes, Price and Steuber');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (57, 'Parker-Steuber');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (58, 'Keeling, Hoppe and Walsh');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (59, 'Monahan-Conn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (60, 'Smitham-Koepp');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (61, 'Kozey, Heller and Pfeffer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (62, 'Quigley-Wiza');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (63, 'Konopelski, Howe and Robel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (64, 'Mayert, Leuschke and Mueller');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (65, 'Dach-Luettgen');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (66, 'Prohaska-Gleason');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (67, 'Upton, Klocko and Lindgren');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (68, 'Donnelly PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (69, 'Sporer-Gutmann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (70, 'Kozey Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (71, 'Kuphal, Grimes and Koss');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (72, 'Donnelly-Larkin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (73, 'Prohaska LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (74, 'Zulauf and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (75, 'Hegmann Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (76, 'Christiansen-Murazik');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (77, 'Cartwright, Monahan and Bernhard');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (78, 'Thiel, Volkman and Gutmann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (79, 'Hilll-Rosenbaum');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (80, 'Barrows LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (81, 'Huel-Terry');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (82, 'Ziemann-Reilly');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (83, 'Padberg-Nicolas');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (84, 'Rolfson-Wiegand');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (85, 'Reynolds, Ernser and Donnelly');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (86, 'Roob-Metz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (87, 'Nader Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (88, 'Osinski-Funk');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (89, 'Bashirian Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (90, 'Schmitt Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (91, 'Ledner PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (92, 'Bayer-Torphy');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (93, 'Bailey, Braun and Bogisich');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (94, 'Stamm Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (95, 'Reinger, Berge and Howell');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (96, 'Medhurst Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (97, 'Barton-Sipes');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (98, 'Schuster, Kassulke and Schowalter');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (99, 'Casper Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (100, 'Predovic-D\'Amore');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (101, 'Renner and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (102, 'Gutmann-Kunde');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (103, 'Bednar LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (104, 'Lakin-Jenkins');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (105, 'Sawayn, Labadie and Kemmer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (106, 'Streich-Flatley');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (107, 'Beahan PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (108, 'Rutherford Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (109, 'Fadel, Ledner and Kohler');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (110, 'Mraz, Koch and Bruen');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (111, 'Legros-Reynolds');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (112, 'Crooks and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (113, 'Yost, Reinger and Funk');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (114, 'Davis PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (115, 'Bartell, Howe and Hilll');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (116, 'Rath, Hickle and Lemke');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (117, 'Wisozk-Krajcik');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (118, 'Walsh PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (119, 'Ullrich-Murray');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (120, 'King-McCullough');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (121, 'Heathcote, D\'Amore and Jaskolski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (122, 'Mohr Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (123, 'Fisher, Marks and Rice');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (124, 'Blick-Roberts');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (125, 'O\'Reilly, Wunsch and Hahn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (126, 'Kessler-Franecki');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (127, 'Raynor-Zemlak');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (128, 'Reynolds, Schroeder and Lueilwitz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (129, 'Wolff Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (130, 'Dooley, Nader and Koepp');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (131, 'Hyatt, Herman and Kris');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (132, 'Wolf PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (133, 'Witting-Kessler');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (134, 'Bauch-Eichmann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (135, 'Carroll-Roberts');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (136, 'Purdy LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (137, 'Konopelski-Carroll');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (138, 'Volkman, Thiel and Champlin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (139, 'Aufderhar, Collier and Mante');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (140, 'Zemlak Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (141, 'Moore, Tromp and Thiel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (142, 'Gutkowski PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (143, 'Monahan Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (144, 'Hirthe, Yundt and Conn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (145, 'Fahey and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (146, 'Schiller, Runolfsson and Gusikowski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (147, 'Lueilwitz LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (148, 'Schaefer-Parker');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (149, 'Ryan-Morar');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (150, 'Graham-Rau');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (151, 'Dickens and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (152, 'Streich, Conn and McLaughlin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (153, 'Daniel-Kuhn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (154, 'Jenkins, Wyman and Schoen');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (155, 'Grant, Buckridge and Stiedemann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (156, 'Herman, Rempel and Kiehn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (157, 'Walsh-Will');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (158, 'Larkin, Predovic and Turcotte');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (159, 'Jacobson, Kuhn and Hintz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (160, 'Beatty LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (161, 'Mante and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (162, 'Leuschke, Lakin and Tremblay');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (163, 'Rodriguez, Raynor and Torphy');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (164, 'Schoen, Homenick and Howell');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (165, 'Dickens-Lowe');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (166, 'Thompson, Murazik and Howell');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (167, 'Eichmann, Gislason and Torphy');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (168, 'Stoltenberg-Rohan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (169, 'Legros Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (170, 'Wehner-Bednar');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (171, 'Wiegand Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (172, 'Larkin-Kuhn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (173, 'Weber, Eichmann and Reinger');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (174, 'Jacobi, Swaniawski and Littel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (175, 'Grant-Langworth');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (176, 'Padberg and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (177, 'Bashirian, Schroeder and Lueilwitz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (178, 'Green-Casper');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (179, 'Lesch and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (180, 'Johnson, Cole and White');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (181, 'Bernier, Ernser and Littel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (182, 'Wilderman, White and Botsford');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (183, 'O\'Conner, Spinka and Auer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (184, 'Robel, Gusikowski and Labadie');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (185, 'Schiller, O\'Conner and Schneider');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (186, 'O\'Conner, Denesik and O\'Reilly');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (187, 'Kautzer Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (188, 'Osinski, Kris and Wiegand');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (189, 'Wyman, Kunze and Durgan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (190, 'Smith PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (191, 'Gusikowski Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (192, 'Simonis LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (193, 'Fritsch-Kutch');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (194, 'Witting LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (195, 'Cummings Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (196, 'Heller Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (197, 'Pouros and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (198, 'Beer and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (199, 'Gleason-Mohr');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (200, 'Nitzsche PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (201, 'Hudson Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (202, 'Johnston LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (203, 'Pacocha Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (204, 'Dare, Huels and Reichert');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (205, 'Zemlak-Kihn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (206, 'Steuber, Tromp and Hickle');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (207, 'Hansen-Hessel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (208, 'Huels, Christiansen and Mann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (209, 'Lesch Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (210, 'Littel, Walter and Crooks');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (211, 'Mertz, Ratke and West');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (212, 'Thiel-Krajcik');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (213, 'Bins, Crooks and Cassin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (214, 'Koch LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (215, 'Willms, Brown and Walsh');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (216, 'Franecki, Blick and Kassulke');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (217, 'Beer-Schmitt');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (218, 'Schuster-Jacobs');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (219, 'Hilpert Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (220, 'Goodwin, Hudson and Rice');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (221, 'Braun, King and Goldner');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (222, 'Towne Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (223, 'Schimmel PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (224, 'Rosenbaum, Fritsch and Tromp');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (225, 'Simonis LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (226, 'Rau PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (227, 'Oberbrunner-Weber');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (228, 'Hane-Satterfield');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (229, 'Balistreri Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (230, 'Reichel, Johnston and Hudson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (231, 'Muller-Green');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (232, 'Weber, Beahan and Daugherty');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (233, 'Buckridge, Kilback and Durgan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (234, 'Hartmann Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (235, 'Monahan-Daniel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (236, 'Rippin, Rath and Nienow');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (237, 'O\'Reilly LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (238, 'Kreiger Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (239, 'Crist-Cassin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (240, 'Hegmann-Bradtke');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (241, 'Willms-Willms');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (242, 'Lind-Lueilwitz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (243, 'Mante, Swaniawski and King');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (244, 'Schamberger PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (245, 'Paucek-Walter');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (246, 'Franecki-Rutherford');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (247, 'Kuhic Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (248, 'Klocko-Rice');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (249, 'Feeney, Mayer and Schroeder');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (250, 'Beier-Hermiston');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (251, 'Metz, Schaden and Harvey');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (252, 'Becker-Hand');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (253, 'Fahey-Hilpert');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (254, 'Greenfelder-Grady');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (255, 'Jerde-Becker');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (256, 'Jerde Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (257, 'Watsica LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (258, 'Medhurst Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (259, 'Kuphal, Kuvalis and Bednar');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (260, 'Howe and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (261, 'Kub-Conroy');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (262, 'Homenick-Langworth');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (263, 'Kihn, Kerluke and Cartwright');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (264, 'Cole Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (265, 'Lubowitz, Braun and Beatty');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (266, 'Schimmel, Wolf and Harvey');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (267, 'Klein, Prosacco and Wiza');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (268, 'Greenfelder-Murazik');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (269, 'Jacobs LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (270, 'Boyle PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (271, 'Willms Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (272, 'Koch-Hermiston');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (273, 'Armstrong, Pouros and Streich');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (274, 'Bernier, Metz and Senger');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (275, 'Schinner Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (276, 'Little Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (277, 'Macejkovic-Aufderhar');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (278, 'Lueilwitz-Eichmann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (279, 'McLaughlin, Wolff and Boyer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (280, 'Schamberger, Kozey and Schinner');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (281, 'Spencer, Gutkowski and Nolan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (282, 'Gutmann, Osinski and Wisozk');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (283, 'Robel Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (284, 'Ferry PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (285, 'Hilll, Heller and Block');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (286, 'Fadel-Mueller');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (287, 'Kohler-Purdy');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (288, 'Lebsack-Senger');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (289, 'Klocko, Goldner and Haley');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (290, 'Howe Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (291, 'Anderson and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (292, 'Kuhlman Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (293, 'Ritchie-Champlin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (294, 'Reichert, Ondricka and Hickle');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (295, 'Schiller Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (296, 'Monahan, O\'Reilly and Lindgren');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (297, 'Walsh, Rau and Botsford');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (298, 'Purdy, Schumm and Jacobs');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (299, 'Hirthe PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (300, 'Hagenes-Kuvalis');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (301, 'Morissette, Metz and Brekke');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (302, 'Schinner, Feest and Kulas');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (303, 'Leannon-Gutmann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (304, 'Hickle-Macejkovic');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (305, 'Klocko, Prohaska and Wunsch');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (306, 'Botsford-Langosh');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (307, 'Strosin-Bogan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (308, 'Gislason, McKenzie and Considine');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (309, 'Blick Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (310, 'Von, Breitenberg and Prohaska');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (311, 'Schmidt Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (312, 'Wolf-Hettinger');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (313, 'Adams Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (314, 'Borer-O\'Reilly');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (315, 'Yost Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (316, 'Fisher-Treutel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (317, 'Runolfsdottir, Gleichner and Bauch');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (318, 'Ziemann-Schneider');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (319, 'Yost, Rath and Zboncak');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (320, 'Stark-McGlynn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (321, 'Towne-Rohan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (322, 'Herman, Hermiston and Grant');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (323, 'Reynolds, Kautzer and Dicki');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (324, 'Tremblay-Kub');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (325, 'Pagac Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (326, 'Zulauf PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (327, 'Pacocha Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (328, 'Skiles-Witting');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (329, 'Abshire PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (330, 'Baumbach, O\'Conner and Russel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (331, 'Predovic Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (332, 'Stehr-Schoen');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (333, 'Hauck LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (334, 'Daugherty, Tillman and Wehner');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (335, 'Douglas-Schimmel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (336, 'O\'Keefe PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (337, 'Parker, Jenkins and Rempel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (338, 'West-Stroman');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (339, 'Keeling and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (340, 'Nitzsche Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (341, 'Rodriguez-Kunze');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (342, 'Bode, Robel and Bednar');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (343, 'Lakin Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (344, 'Bahringer, Gutkowski and Gislason');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (345, 'Cartwright PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (346, 'Kassulke and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (347, 'Hilll LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (348, 'Lebsack Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (349, 'Rempel PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (350, 'Klein PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (351, 'Welch PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (352, 'Flatley, Boyle and Hamill');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (353, 'Corkery, Bednar and Harris');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (354, 'Bashirian, Nitzsche and Rau');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (355, 'Zulauf-Yost');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (356, 'Koepp LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (357, 'Waelchi Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (358, 'Bechtelar Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (359, 'Dickens PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (360, 'Jast-Ledner');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (361, 'Kub-Blanda');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (362, 'Kohler and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (363, 'Mosciski Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (364, 'Sauer-Zemlak');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (365, 'Runte-Miller');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (366, 'Torp, Ullrich and Welch');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (367, 'Kihn-Bergnaum');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (368, 'Ziemann and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (369, 'Breitenberg Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (370, 'Glover, Ferry and Reilly');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (371, 'Prohaska, Champlin and Smith');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (372, 'Marvin and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (373, 'Sporer-Parisian');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (374, 'Purdy-Terry');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (375, 'Wyman PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (376, 'Bogan, Paucek and Carroll');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (377, 'Corkery PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (378, 'Kassulke, Ankunding and Kuhlman');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (379, 'Thiel-Baumbach');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (380, 'Farrell, Block and Schmeler');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (381, 'Carroll-Torp');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (382, 'Russel Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (383, 'Cartwright-Rutherford');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (384, 'Schulist, Kshlerin and Abbott');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (385, 'Labadie, Kutch and Shields');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (386, 'Howell-Fadel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (387, 'Howell, Fay and Lockman');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (388, 'Schimmel, Kuhn and McGlynn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (389, 'Nader, Trantow and Stroman');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (390, 'Eichmann, Morar and Haley');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (391, 'Connelly-Kozey');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (392, 'Sawayn-Kunde');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (393, 'Konopelski-DuBuque');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (394, 'Cassin-Walker');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (395, 'Berge-Howell');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (396, 'McGlynn, Cassin and Lakin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (397, 'Rohan-Gerhold');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (398, 'Gleichner, Shields and Daugherty');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (399, 'Will, Braun and Nader');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (400, 'Gleason PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (401, 'Barton-Mertz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (402, 'Bogisich-Reynolds');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (403, 'Shanahan-Gleason');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (404, 'Krajcik Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (405, 'Fritsch-Padberg');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (406, 'Langworth, Kunze and Franecki');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (407, 'Reichel-Bednar');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (408, 'Raynor, Zulauf and Bednar');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (409, 'Jakubowski, Rice and Fay');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (410, 'Mante Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (411, 'Glover LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (412, 'Dickinson Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (413, 'Jacobs and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (414, 'Emard, Kunze and Bernier');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (415, 'Eichmann, Mante and Kihn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (416, 'Hackett and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (417, 'Carroll LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (418, 'Quitzon, Toy and Rutherford');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (419, 'Pollich-Abshire');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (420, 'Stokes-Waelchi');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (421, 'VonRueden Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (422, 'Pagac Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (423, 'Carter, Buckridge and Bednar');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (424, 'Greenholt-Kub');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (425, 'McCullough Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (426, 'Lebsack-Walsh');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (427, 'Romaguera-Lowe');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (428, 'Gerlach-Bednar');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (429, 'Emmerich Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (430, 'Flatley-Graham');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (431, 'Denesik-Dicki');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (432, 'Reinger Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (433, 'Ferry and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (434, 'Daugherty PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (435, 'Ratke-Boyle');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (436, 'Streich Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (437, 'Carter and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (438, 'Hauck, Blanda and Langworth');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (439, 'Mante PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (440, 'Homenick LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (441, 'Romaguera PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (442, 'Torphy, Rice and Rodriguez');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (443, 'Schaefer-Hand');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (444, 'Reichert-Hegmann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (445, 'Reichel-Koch');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (446, 'Muller Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (447, 'Wolf-Smith');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (448, 'Kohler, Torphy and McDermott');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (449, 'Hermann, Hoeger and Brown');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (450, 'Lemke-Lakin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (451, 'Rau LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (452, 'Crooks, Gutkowski and Dooley');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (453, 'Altenwerth, Boehm and Cremin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (454, 'Smith-Grimes');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (455, 'Thiel Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (456, 'Murazik Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (457, 'Stark, Reichert and Konopelski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (458, 'Lebsack Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (459, 'Thompson-McClure');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (460, 'Bernier, Denesik and Dibbert');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (461, 'Morissette-West');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (462, 'Spinka-Cummerata');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (463, 'Shanahan, Bins and Hyatt');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (464, 'Conn, Ziemann and Senger');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (465, 'Simonis, Stiedemann and Walsh');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (466, 'Dietrich-Beier');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (467, 'Pfannerstill, O\'Keefe and Ritchie');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (468, 'Mosciski, Prosacco and Schuppe');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (469, 'Schultz-Wehner');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (470, 'Rogahn LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (471, 'Durgan Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (472, 'Mante-Runte');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (473, 'Borer, Bogisich and Labadie');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (474, 'Schultz-Ebert');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (475, 'Homenick-Kulas');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (476, 'Jaskolski-Ullrich');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (477, 'Kertzmann Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (478, 'Klocko-Reilly');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (479, 'Schinner-Collins');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (480, 'Cummings-Tillman');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (481, 'Cremin-Moen');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (482, 'Lebsack, Batz and Pouros');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (483, 'Schaden and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (484, 'Wiza-Welch');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (485, 'Leffler, Hane and Waelchi');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (486, 'Lang and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (487, 'Nikolaus Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (488, 'Buckridge PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (489, 'Powlowski, Funk and Hirthe');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (490, 'Lynch-Jacobson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (491, 'Greenholt LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (492, 'Pollich-Little');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (493, 'Jacobs Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (494, 'Wyman LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (495, 'Rempel LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (496, 'Wunsch LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (497, 'Turcotte-Mann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (498, 'Windler-Eichmann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (499, 'Osinski Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (500, 'Doyle PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (501, 'Ortiz PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (502, 'Langosh, Harris and Olson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (503, 'Labadie-Friesen');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (504, 'Hamill-Padberg');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (505, 'Aufderhar, Hilll and King');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (506, 'Friesen, Williamson and Klocko');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (507, 'Cole-Will');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (508, 'Kunde PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (509, 'Mills, Herman and Dach');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (510, 'Marquardt-Leffler');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (511, 'Johnston PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (512, 'Blick, Wehner and Hettinger');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (513, 'Marquardt and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (514, 'Jerde, Gusikowski and Stiedemann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (515, 'Schneider-Farrell');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (516, 'Hermann-Anderson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (517, 'Windler, Murazik and Hammes');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (518, 'Stracke, Cronin and Hammes');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (519, 'Watsica PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (520, 'Swaniawski PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (521, 'Quitzon Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (522, 'Grady-Kiehn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (523, 'Strosin-Brakus');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (524, 'Sanford-Larson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (525, 'Haley, Hartmann and Williamson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (526, 'Wilkinson LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (527, 'Kessler-Halvorson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (528, 'Yost and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (529, 'Cole, Hermiston and Marquardt');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (530, 'Welch LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (531, 'Kreiger-Ondricka');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (532, 'Roberts, White and West');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (533, 'Mertz-Tremblay');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (534, 'Schmitt-Murphy');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (535, 'Lesch LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (536, 'Jones Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (537, 'Strosin and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (538, 'Walter, Wuckert and Hammes');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (539, 'Welch LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (540, 'Schaden and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (541, 'Lowe-Kunde');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (542, 'Cormier-Bartell');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (543, 'Carter-Halvorson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (544, 'Howell-Marquardt');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (545, 'Bode-Mosciski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (546, 'Parisian, Willms and Macejkovic');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (547, 'Ankunding-Bergnaum');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (548, 'Hermann, Fritsch and Bartoletti');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (549, 'Ledner Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (550, 'Bradtke-Ortiz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (551, 'Schuppe LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (552, 'Jones Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (553, 'Dickens Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (554, 'VonRueden-Sauer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (555, 'Sawayn, Maggio and Murazik');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (556, 'Hoppe Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (557, 'Rice, Schowalter and Rau');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (558, 'Brekke, Jakubowski and Miller');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (559, 'Eichmann Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (560, 'Heathcote-Shanahan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (561, 'Lind Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (562, 'Schowalter-Weimann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (563, 'Stehr-Koch');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (564, 'Dooley, Mraz and Schultz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (565, 'Cassin Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (566, 'Runolfsson Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (567, 'Yost-Kertzmann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (568, 'Willms-Aufderhar');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (569, 'O\'Kon and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (570, 'Gaylord, Marvin and Reichert');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (571, 'Stark Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (572, 'Jones, Durgan and Labadie');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (573, 'Feil, Oberbrunner and Hamill');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (574, 'Hintz-Sipes');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (575, 'Wyman, West and Heidenreich');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (576, 'Kuhic and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (577, 'Witting, Swaniawski and Heathcote');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (578, 'Dare, Rogahn and Hartmann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (579, 'Mohr, Sawayn and Block');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (580, 'Schmidt, Klein and Auer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (581, 'Braun-Collier');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (582, 'Walker LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (583, 'Hauck-Boyer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (584, 'Kuvalis Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (585, 'Fritsch PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (586, 'Hilpert, Kirlin and Roob');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (587, 'Pacocha-Klocko');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (588, 'O\'Kon, Gaylord and Bednar');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (589, 'Greenfelder-Ward');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (590, 'Wilkinson, Christiansen and Franecki');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (591, 'Lemke Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (592, 'Barton and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (593, 'Gusikowski-Torp');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (594, 'Corkery-Rodriguez');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (595, 'Morar, Shields and Beatty');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (596, 'Jenkins Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (597, 'Roob PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (598, 'Armstrong, VonRueden and Pouros');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (599, 'Hirthe Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (600, 'Ortiz PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (601, 'Bahringer, Grant and Schuppe');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (602, 'Glover, Boehm and Dooley');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (603, 'Little and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (604, 'Greenfelder PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (605, 'Toy, Morissette and Farrell');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (606, 'Hegmann Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (607, 'Koch Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (608, 'Aufderhar PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (609, 'Thompson-Balistreri');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (610, 'Eichmann, Nikolaus and Rice');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (611, 'Haley-Herman');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (612, 'Wolf Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (613, 'Pfannerstill, Rowe and Champlin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (614, 'Vandervort-Stehr');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (615, 'Ward-Raynor');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (616, 'Kutch, Haag and Monahan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (617, 'Wolff, Auer and Conroy');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (618, 'Hettinger, Nader and Beatty');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (619, 'Roob LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (620, 'Carroll Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (621, 'Prohaska Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (622, 'Jast, Veum and Lindgren');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (623, 'VonRueden, Adams and Walker');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (624, 'Ryan-Strosin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (625, 'Rolfson, Goyette and Brakus');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (626, 'Leffler-O\'Conner');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (627, 'Franecki, Dach and Moore');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (628, 'Block Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (629, 'Daugherty, Tillman and Bernier');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (630, 'Simonis Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (631, 'Sporer-McClure');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (632, 'Botsford-Hintz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (633, 'Frami, Crooks and Rath');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (634, 'Schinner and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (635, 'Macejkovic LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (636, 'Weimann-Shanahan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (637, 'Stroman, Mraz and Schuster');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (638, 'Gleason Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (639, 'Dibbert and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (640, 'Krajcik Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (641, 'Okuneva Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (642, 'Mohr, Gutkowski and Hansen');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (643, 'Heller Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (644, 'Nicolas PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (645, 'McCullough-Emard');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (646, 'Klein, Christiansen and Becker');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (647, 'Gulgowski, Stehr and Goyette');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (648, 'Weber Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (649, 'Kling LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (650, 'Douglas-McClure');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (651, 'Rau-Cole');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (652, 'Vandervort and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (653, 'Kessler, Huels and Bogan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (654, 'Mann, Sporer and Marvin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (655, 'Shanahan-Huels');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (656, 'Kiehn PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (657, 'Schroeder LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (658, 'Little, Kunde and Boyer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (659, 'Casper and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (660, 'Prosacco Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (661, 'Runolfsson, Doyle and Davis');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (662, 'Hickle, Barrows and Rice');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (663, 'Hayes, Tremblay and Pouros');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (664, 'Weber-Stroman');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (665, 'Hirthe, Nienow and Terry');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (666, 'Dickinson-Dietrich');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (667, 'Olson, Jenkins and Ebert');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (668, 'Yost-Gibson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (669, 'Blick, Robel and Jakubowski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (670, 'Klocko, Lindgren and Altenwerth');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (671, 'Bauch Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (672, 'Brekke-Mayert');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (673, 'Hyatt-Schamberger');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (674, 'Ledner PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (675, 'Runte LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (676, 'Sporer LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (677, 'Cole, Sawayn and Bartell');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (678, 'Watsica and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (679, 'Schaefer-Emmerich');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (680, 'Mohr Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (681, 'Green, Abernathy and Torphy');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (682, 'Rowe-Cruickshank');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (683, 'Cummings, Bogan and Maggio');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (684, 'Harber, Metz and Anderson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (685, 'Gutmann PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (686, 'Heaney-Cartwright');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (687, 'Emmerich PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (688, 'Carroll and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (689, 'Beatty, Kirlin and Douglas');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (690, 'Stark-Stanton');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (691, 'Ratke, Koelpin and White');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (692, 'Kozey-Fay');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (693, 'Metz, Prohaska and Wunsch');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (694, 'Beier-Koepp');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (695, 'Hartmann, Marks and Schuster');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (696, 'Dickinson Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (697, 'Price, Stark and Wolf');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (698, 'Beahan, Hoppe and Jaskolski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (699, 'Bashirian, Denesik and Reichel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (700, 'Corwin-Batz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (701, 'Macejkovic-Lindgren');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (702, 'Heller Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (703, 'Schmeler, Heaney and Gulgowski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (704, 'Hermiston, Kiehn and Effertz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (705, 'Howell, Berge and Breitenberg');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (706, 'Bernier, Reichel and Heidenreich');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (707, 'Ernser, Ebert and Friesen');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (708, 'Connelly, Jacobi and Botsford');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (709, 'Brekke-Hermiston');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (710, 'Greenholt-Spinka');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (711, 'Reynolds LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (712, 'Corkery, Bergstrom and Fadel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (713, 'Torphy, Hudson and Harvey');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (714, 'Champlin, Senger and Hartmann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (715, 'Macejkovic, Larkin and Klocko');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (716, 'Reynolds-McClure');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (717, 'Skiles, Hudson and Terry');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (718, 'Thompson, Auer and Pollich');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (719, 'Veum, Goodwin and Stehr');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (720, 'Aufderhar-Monahan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (721, 'Sanford-Waters');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (722, 'Hartmann-Sipes');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (723, 'Cassin, Crona and Russel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (724, 'Sauer-Christiansen');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (725, 'Ratke-Gerlach');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (726, 'Runolfsson, Wilkinson and Parker');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (727, 'Mitchell, Cormier and Jacobi');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (728, 'Swift Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (729, 'Price LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (730, 'Dicki Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (731, 'Rath-Abernathy');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (732, 'Stiedemann Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (733, 'Pfannerstill and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (734, 'Kris-Russel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (735, 'White, Zulauf and Osinski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (736, 'Russel LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (737, 'Dicki Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (738, 'Lockman Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (739, 'Kovacek, Rutherford and O\'Keefe');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (740, 'Witting and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (741, 'Nienow, Hyatt and Schoen');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (742, 'Johnston LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (743, 'Abbott, Ortiz and Cronin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (744, 'Senger, Jerde and Monahan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (745, 'Vandervort-Russel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (746, 'Armstrong-Tillman');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (747, 'Kuhic, Durgan and Cartwright');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (748, 'Zboncak-Brown');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (749, 'Bruen-Bergnaum');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (750, 'Turcotte, Runte and Ankunding');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (751, 'Lueilwitz PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (752, 'Satterfield LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (753, 'Dare PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (754, 'Ledner, Swaniawski and Larson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (755, 'Herman-Auer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (756, 'Ryan-Kertzmann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (757, 'Mayer-Nienow');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (758, 'Senger LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (759, 'Toy-Sauer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (760, 'Macejkovic-Corwin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (761, 'Borer, Romaguera and O\'Conner');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (762, 'Raynor Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (763, 'Heidenreich-Powlowski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (764, 'Funk Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (765, 'Schneider LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (766, 'Keeling Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (767, 'Nitzsche-Fay');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (768, 'Boehm PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (769, 'Ruecker and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (770, 'Stark-Grant');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (771, 'Gislason-Hermann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (772, 'Adams-Huel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (773, 'Hauck-Renner');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (774, 'Towne, Thiel and Gerhold');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (775, 'Rosenbaum Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (776, 'Daniel, Altenwerth and Kreiger');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (777, 'Schowalter Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (778, 'Dibbert LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (779, 'Reilly, Fisher and Kutch');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (780, 'Gaylord-Willms');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (781, 'Gerlach-Rowe');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (782, 'Gleason and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (783, 'Jaskolski Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (784, 'Wyman-Emard');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (785, 'Lueilwitz, Flatley and Witting');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (786, 'Johnston, Beier and Champlin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (787, 'Rice-Balistreri');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (788, 'Adams and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (789, 'Muller, DuBuque and Hickle');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (790, 'Emmerich-Sporer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (791, 'Prohaska, Braun and Marquardt');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (792, 'Stehr, Klocko and Emmerich');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (793, 'Renner-Waelchi');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (794, 'Volkman-Fritsch');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (795, 'D\'Amore and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (796, 'Stark and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (797, 'Hodkiewicz, Johnson and Pfeffer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (798, 'Reichert-Homenick');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (799, 'Schaefer-Jakubowski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (800, 'Moore-Glover');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (801, 'Pfeffer-Sawayn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (802, 'Brown, Sipes and Auer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (803, 'Dare, Denesik and Labadie');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (804, 'Pagac, Anderson and Steuber');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (805, 'Wolf, Pfeffer and Ondricka');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (806, 'Walker, Jakubowski and Quigley');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (807, 'Macejkovic, Mayert and Shields');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (808, 'Heaney, Effertz and Crist');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (809, 'Mertz-Keebler');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (810, 'Pollich-Pollich');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (811, 'Kilback, Borer and Wolff');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (812, 'Brown, O\'Connell and Balistreri');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (813, 'Hauck LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (814, 'Johnston-Mills');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (815, 'Cremin PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (816, 'Treutel and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (817, 'Sipes Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (818, 'Schroeder, Muller and Jacobi');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (819, 'Smith and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (820, 'Dare Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (821, 'Kshlerin, O\'Conner and Zboncak');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (822, 'Jacobs LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (823, 'Considine, Hackett and Johns');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (824, 'Dach, Schmidt and Lubowitz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (825, 'Heathcote, Hegmann and Ortiz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (826, 'Glover-Hammes');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (827, 'Lind, Senger and Langosh');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (828, 'Murazik-Jakubowski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (829, 'Harvey LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (830, 'Mueller-Harber');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (831, 'Wunsch-Walter');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (832, 'Hills Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (833, 'Kub-Schmidt');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (834, 'Thiel, Goyette and O\'Conner');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (835, 'Boyle-Schumm');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (836, 'Cremin LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (837, 'Koss, Lynch and Kub');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (838, 'Doyle-Sporer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (839, 'Dicki-Willms');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (840, 'Cruickshank Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (841, 'White, Flatley and Keeling');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (842, 'Ferry-Bernhard');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (843, 'Jast-Turcotte');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (844, 'Hammes Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (845, 'Beatty PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (846, 'Zieme, Macejkovic and Carter');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (847, 'Gorczany, Koss and Swaniawski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (848, 'Brekke, Muller and Cole');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (849, 'Ryan, Trantow and Ondricka');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (850, 'Ortiz-Gusikowski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (851, 'Champlin, Dickinson and Labadie');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (852, 'Rath-Ortiz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (853, 'Crona LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (854, 'McCullough-Nolan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (855, 'Romaguera Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (856, 'Haag, Quigley and Wintheiser');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (857, 'Mayer LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (858, 'Beahan and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (859, 'Kshlerin and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (860, 'Swift PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (861, 'Green, Dicki and Rolfson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (862, 'Muller-Powlowski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (863, 'Sipes-Kuphal');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (864, 'Medhurst, Lemke and Bartoletti');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (865, 'Gorczany, Strosin and Yundt');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (866, 'Conroy-Schmitt');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (867, 'Cremin-Gutmann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (868, 'Lynch-Witting');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (869, 'Senger, Schaefer and Rowe');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (870, 'Bosco-Yost');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (871, 'Hane Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (872, 'Schinner, Gerhold and Bergnaum');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (873, 'Wiza-Gleichner');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (874, 'Stoltenberg, Lindgren and Hegmann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (875, 'Batz Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (876, 'Corwin and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (877, 'Romaguera-Crist');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (878, 'Schimmel Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (879, 'White, Konopelski and Swift');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (880, 'Wyman PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (881, 'Effertz-Sawayn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (882, 'Zemlak, Kemmer and Rempel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (883, 'Schultz-Kohler');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (884, 'Schneider LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (885, 'Renner, Tillman and Altenwerth');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (886, 'Hansen, O\'Kon and Fritsch');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (887, 'Murphy-Durgan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (888, 'Leannon-Donnelly');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (889, 'Goodwin Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (890, 'Hoeger, Flatley and Erdman');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (891, 'Hane-Block');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (892, 'Beatty, Boyer and Friesen');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (893, 'Crist, Stanton and Wiza');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (894, 'Prosacco-Ullrich');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (895, 'Nolan Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (896, 'Grady, Huels and Lueilwitz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (897, 'Goyette and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (898, 'McClure, Schiller and Mayer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (899, 'Nolan, Larson and Bashirian');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (900, 'Stokes and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (901, 'Cummerata and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (902, 'Walsh, Torphy and Jakubowski');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (903, 'Wuckert-Koch');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (904, 'Stamm, Roob and Cummerata');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (905, 'Hayes-Schumm');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (906, 'Nader, Corwin and Schuster');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (907, 'Streich-Schumm');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (908, 'Hoppe-Zemlak');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (909, 'Feeney PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (910, 'Zieme-Lowe');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (911, 'Hoeger LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (912, 'McCullough, Gaylord and Quigley');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (913, 'O\'Conner PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (914, 'Treutel, Swaniawski and Kilback');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (915, 'Dare-Hessel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (916, 'Heller, O\'Kon and Turcotte');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (917, 'Simonis and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (918, 'Thiel-Jones');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (919, 'Schuppe Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (920, 'Boyle Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (921, 'Dickinson, Hayes and Hilpert');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (922, 'Harvey-Skiles');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (923, 'McDermott LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (924, 'Quigley, Pacocha and Rosenbaum');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (925, 'Fahey-O\'Connell');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (926, 'Rodriguez-Homenick');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (927, 'Kuvalis-Kuhic');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (928, 'Greenfelder, Larson and Goldner');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (929, 'Doyle LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (930, 'Anderson Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (931, 'Nicolas-Frami');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (932, 'Botsford-Hermann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (933, 'Crist-Fay');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (934, 'Medhurst, Cronin and Ledner');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (935, 'Beer Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (936, 'Reynolds and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (937, 'Mayer-Beahan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (938, 'Kuvalis Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (939, 'Hoppe and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (940, 'Spinka and Sons');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (941, 'Mills Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (942, 'Jacobson PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (943, 'Heaney LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (944, 'Jakubowski-Lueilwitz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (945, 'Schmitt, Schultz and Willms');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (946, 'Lemke PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (947, 'Kihn-Brekke');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (948, 'Legros Group');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (949, 'Keebler LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (950, 'Collins-Mayert');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (951, 'O\'Keefe-Schowalter');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (952, 'Greenfelder LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (953, 'Hartmann-Rau');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (954, 'Labadie, Rice and Armstrong');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (955, 'Yundt Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (956, 'Schinner, Schmeler and Rempel');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (957, 'Morissette, Wolff and Ryan');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (958, 'Johns-Luettgen');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (959, 'Cummerata LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (960, 'Metz, Murazik and Jenkins');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (961, 'Aufderhar-Turcotte');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (962, 'Rau-Kshlerin');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (963, 'Jenkins Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (964, 'Bauch-Hagenes');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (965, 'Schimmel-Nikolaus');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (966, 'Balistreri Ltd');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (967, 'Russel-Stark');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (968, 'Torp-Deckow');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (969, 'Stokes-Bins');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (970, 'Powlowski-Buckridge');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (971, 'Willms Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (972, 'Krajcik PLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (973, 'Harber, Jacobi and Leffler');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (974, 'Stamm, Feeney and Hansen');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (975, 'VonRueden-Nienow');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (976, 'Thiel-O\'Connell');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (977, 'Purdy, Rosenbaum and Gottlieb');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (978, 'Grant LLC');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (979, 'Stroman, Lubowitz and Erdman');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (980, 'Kunde-West');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (981, 'McClure Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (982, 'Koch-Jones');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (983, 'Volkman, West and Gibson');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (984, 'Streich, Brakus and Stoltenberg');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (985, 'Bartoletti-Medhurst');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (986, 'Mitchell, Labadie and Flatley');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (987, 'Jast-Kautzer');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (988, 'Grimes, Nader and Nienow');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (989, 'Goldner-Conn');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (990, 'Kulas, Mueller and Harris');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (991, 'Waters-Abbott');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (992, 'Champlin, Schimmel and Adams');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (993, 'Abbott-Considine');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (994, 'Hermann, Steuber and O\'Connell');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (995, 'Hamill Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (996, 'Leffler, Gerlach and Hintz');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (997, 'Kub Inc');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (998, 'Stark, Kohler and Gutmann');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (999, 'Koelpin, Collier and Harvey');
INSERT INTO `Categoria` (`id_categoria`, `nome`) VALUES (1000, 'Block Ltd');
